### ISSUE TITLE
Oops! Something went wrong with You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by KimDoYoung1997** [mhubii/chatgpt_turtlesim#3]
hello. Thank you for sharing repository first.. It will be really helpful for me.

# problem occured 

by following your tutorial,

### In first terminal
$ ros2 run turtlesim turtlesim_node

### In second terminal
$ ros2 launch rosbridge_server rosbridge_websocket_launch.xml

### In third terminal
$ python3 main.py --key your_key
when I command this, in the second terminal  "[rosbridge_websocket-1] [INFO] [1685638191.613941535] [rosbridge_websocket]: Client connected. 1 clients total." message published. I think my local pc and openai web is connected well at this moment.
![image](https://github.com/mhubii/chatgpt_turtlesim/assets/97829134/f1465089-9997-4438-8eef-af8defaf20d4)

### ros2 topic 
additionally, this is the state of my ros2 topic
![image](https://github.com/mhubii/chatgpt_turtlesim/assets/97829134/fc7aaac6-e988-46a6-b825-ec2c529f8a94)

## Turtlesim doesn't move
finally, when I prompt in third terminal like this, turtlesim doesn't go ever with this message occured
"Oops! Something went wrong with You exceeded your current quota, please check your plan and billing details..
Done."

can I ask why this problem occured?

++ 
this is **my rosbridge_websocket_launch.xml**
![image](https://github.com/mhubii/chatgpt_turtlesim/assets/97829134/e87ddc13-a638-4db9-87d3-98a753abb1be)

do I have to also add my local ip (for example 192.168.x.x something) to arg name="address" default="" ?? 

Thank you!

**Comment by mhubii** [comment]
Hi @KimDoYoung1997 

please be aware that you just shared a private key with us! Maybe remove the picture or invalidate the key.

That said, this seems to be an issue that you are having with OpenAI. It seems you exceeded your limit for the API usage. Maybe go to openai.com and try to find the issue there. Let me know if this helps

This implementation just sends requests to OpenAI's API

https://github.com/mhubii/chatgpt_turtlesim/blob/61825634a55933d818671fabeaf4ead2cba58439/prompt/openai_interface.py#L46

**Comment by KimDoYoung1997** [comment]
@mhubii  Thank you for reply and advice for API key deletion.

by your answer, I found some link that explains the issues in this link.
[https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details]

As I understand this link , there is no fault in my procedure but only for openai.. is it right??

So, I bough chatgpt4 and I retry all procedures, but I have same problems...

can you give me more advices??? thank you sincerly..

**Comment by mhubii** [comment]
sorry I don't know how to debug openai related issues. Maybe for debugging, try to run a minimal script that calls into the openai API instead of running this repository
